# Generated by Django 3.0.6 on 2020-05-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('storeId', models.IntegerField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=60)),
            ],
        ),
    ]
